#!/usr/bin/env bash
# Copyright (C) 2018 Laboratory of Experimental Biophysics
# Ecole Polytechnique Federale de Lausanne (EPFL), Switzerland
#
# Creates an image for building Micro-Manager 2.0 plugins with Maven.
#
# Usage: ./build TARGET_DIR
#
# TARGET_DIR is the path to the Micro-Manager build artifacts.
#

target_dir=$1

cp Dockerfile ${target_dir}
cp setup ${target_dir}
cd ${target_dir}

docker build \
       -t epflbiophys/micro-manager:mvn-plugin-2.0gamma \
       .

rm Dockerfile || true
rm setup || true
